services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4173:4173"
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    command: ["npm", "run", "dev"]
  user-service:
    build:
      context: ./backend
      dockerfile: user-service/Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - rabbitmq
      - redis
      - mongodb
    environment:
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - USERSECRET=fox
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_URL=mongodb://mongodb:27017/
  product-service:
    build:
      context: ./backend
      dockerfile: product-service/Dockerfile
    ports:
      - "3002:3002"
    depends_on:
      - rabbitmq
      - mongodb
    environment:
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - DB_URL=mongodb://mongodb:27017/
  order-service:
    build:
      context: ./backend
      dockerfile: order-service/Dockerfile
    ports:
      - "3003:3003"
    depends_on:
      - rabbitmq
      - mongodb
    environment:
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - DB_URL=mongodb://mongodb:27017/
  notification-service:
    build:
      context: ./backend
      dockerfile: notification-service/Dockerfile
    ports:
      - "3004:3004"
    depends_on:
      - rabbitmq
      - redis
      - mongodb
    environment:
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_URL=mongodb://mongodb:27017/
  category-service:
    build:
      context: ./backend
      dockerfile: category-service/Dockerfile
    ports:
      - "3005:3005"
    depends_on:
      - rabbitmq
      - redis
      - mongodb
    environment:
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_URL=mongodb://mongodb:27017/
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5673:5672"
      - "15673:15672"
  redis:
    image: redis:latest
    ports:
      - "6380:6379"
  mongodb:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
volumes:
  node_modules: {}
  mongodb_data: {}
